name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  test:
    if: ${{ github.repository }} == 'egibs/reconcile'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            "macos-15-intel",
            "macos-latest",
            "ubuntu-24.04-arm",
            "ubuntu-latest",
            "windows-11-arm",
            "windows-latest",
          ]
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run Tests
        if: runner.os != 'Windows'
        run: |
          make test

      - name: Run Tests (Windows)
        if: runner.os == 'Windows'
        run: |
          make test-win

  bench:
    if: ${{ github.repository }} == 'egibs/reconcile'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            "macos-15-intel",
            "macos-latest",
            "ubuntu-24.04-arm",
            "ubuntu-latest",
            "windows-11-arm",
            "windows-latest",
          ]
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run Benchmarks
        run: |
          make bench

  lint:
    if: ${{ github.repository }} == 'egibs/reconcile'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        target: ["golangci-lint-lint", "gosec", "modernize", "osv", "vet"]
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run make ${{ matrix.target }}
        run: |
          make ${{ matrix.target }}

  fuzz:
    if: ${{ github.repository }} == 'egibs/reconcile'
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            "macos-15-intel",
            "macos-latest",
            "ubuntu-24.04-arm",
            "ubuntu-latest",
            "windows-11-arm",
            "windows-latest",
          ]
        test:
          [
            "FuzzDiffConcurrent",
            "FuzzDiffMain",
            "FuzzDiffMulti",
            "FuzzEmbedded",
            "FuzzEqual",
            "FuzzHashAll",
            "FuzzHashSerial",
            "FuzzResultIterator",
            "FuzzScript",
            "FuzzSoname",
            "FuzzSuffix",
            "FuzzTryMarkConcurrent",
            "FuzzTryMarkSerial",
          ]
    steps:
      - uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Run ${{ matrix.test }}
        if: runner.os != 'Windows'
        run: |
          GOEXPERIMENT=greenteagc go test --fuzz=${{ matrix.test }} -run=${{ matrix.test }} -fuzztime=10s ./pkg/files

      - name: Run ${{ matrix.test }} (Windows)
        if: runner.os == 'Windows'
        run: |
          set "GOEXPERIMENT=greenteagc" & go test --fuzz=${{ matrix.test }} -run=${{ matrix.test }} -fuzztime=10s ./pkg/files
